spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:bookstore;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    open-in-view: false
    properties:
      hibernate.format_sql: true

# Swagger UI keeps default at /swagger-ui.html

# Use this logging for troubleshooting HTTP adapter and outbox (optional)
logging:
  level:
    org.springframework.web.client.RestClient: DEBUG
    org.apache.hc.client5.http: WARN
    com.example.bookstore.common.outbox: INFO

# If you ever switch back to sync HTTP mode:
ordering:
  payments:
    mode: http
    base-url: http://localhost:8080
